'''! @page lab2page.py Lab 2: Incremental Encoders
    @tableofcontents
    Read from a quadrature encoder and return associated data to the user.
    
    @section sec_intro2 Introduction
    In Lab 2, our team developed code to read the signals generated by 
    quadrature encoders and interpret them as the angular position of a motor
    shaft. We also wrote a user interface to interpret user keyboard presses
    as encoder commands, wrapped the encoder commands in a Python class, and 
    formatted our UI and encoder modules as tasks to be run in a main file.
    Please see @ref sec_files2 for descriptions about each of our 
    files.
    
    @section sec_res2 Results
    The following figure shows encoder position data collected over a 30 
    second interval, an optional feature of the User Task.
    @image html Lab2Data.png width=500px
    
    @section sec_files2 Project Files
    Something about the project files.
    
    @subsection sub_main2 Main File
    The main file instantiates our task- and class-files as objects to be run
    asynchronously. Note the task diagram below for information regarding file 
    communication and run frequency. See @ref main.py for more information.
    @image html taskDiagram2.png width=500px
    
    @subsection sub_utask2 User Task
    The user interface is written as a generator function that prints to a 
    terminal emulator, and its state transition diagram may be viewed below. 
    It is able to read a user's keyboard presses as encoder 
    commands, such as zeroing or printing the encoder's position in ticks, 
    over the USB virtual comm port. See @ref UTask.py for more information.
    @image html UTaskSTD.png width=600px
    
    @subsection sub_etask2 Encoder Task
    The encoder task uses a generator function to update a shared tuple, 
    encData, that stores time [ms], position [ticks], and position changes
    [ticks/sec]. See @ref ETask.py for more information.
    @image html ETaskSTD3.png width=500px
    
    @subsection sub_enc2 Encoder Driver
    The encoder driver is a class file that instantiates timer and timer 
    channel objects and has various methods for reading data from the encoder.
    See @ref encoder.py for more information.
    
    @subsection sub_sha2 Shares Class
    The shares class file allows variables to be created, read from, and 
    written to multiple files.
    See @ref shares.py for more information.

'''